#!/usr/bin/env node
var config = require(__dirname + '/config.json');
var Twit = require('twit');
var WebSocket = require('ws');
var ws;

var twit = new Twit(config.twitter);

twit.stream('user').on('tweet', function(data) {
	var color = (data.text.match(/#(?:[0-9a-f]{6}|[0-9a-f]{3})/i) || ['']).shift();

	ws.send(color);
});

(function connect() {
	ws = new WebSocket(config.server);

	console.log('WS: connecting');

	ws.on('open',function open() {
		console.log('WS: connected');
	});

	ws.on('close', function owwy() {
		console.log('WS: disconnected');
		console.log('WS: reconnecting in 1 second');
		setTimeout(connect, 1000);
	});
})();

// vim: set ft=javascript :
